version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.19
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-83-49-109.compute-1.amazonaws.com
            port: '5432'
            database: d8ll4uru6i74la
            user: kpsxnzbduzwtig
            password: d85ebef7c4141f229aecc74b7503bc58df43d688a4c357a1aa6e0f6ceae18ab0
            migrations: true
            rawAccess: true
            ssl: true